version: '3.7'
services:
  node-app:
    build: .\gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: app
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/mnt
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass